version: '3.7'

services:
    php:
        image: php:8.1-cli-alpine
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t .
        environment:
            docker: "true"
        ports:
            - 8080:8080
        volumes:
            - .:/var/www

